// Generated by IcedCoffeeScript 1.6.3-i
(function() {
  exports.parse = function(input) {
    var components, m, x;
    components = null;
    x = /^([^(<]*?)\s+(\((.*?)\)\s+)?<(.*)?>$/;
    if ((m = input.match(x)) != null) {
      components = {
        username: m[1],
        comment: m[3],
        email: m[4]
      };
    }
    return components;
  };

}).call(this);
